[project]
name = "qmap"
version = "0.1.0"
description = "Toolkit for solving the Qubit Mapping Problem."
readme = "README.md"
requires-python = "==3.11.3"
license = {text = "MIT"}
dependencies = [
    "qiskit==0.42.1",
]